### ISSUE TITLE
Cannot specify font properties in template but font from CLI options

### ISSUE THREAD

**Issue by alerque** [sile-typesetter/fontproof#39]
Extracted from [comment here](https://github.com/sile-typesetter/fontproof/pull/38#issuecomment-1489634731):

> After installing the rock I'm able to test the new fontproof on some font existing font projects.
> 
> Looks like when a .sil test file (which we tend to keep under tests/example.sil in various font project repositories) has something like `\setTestFont[features="+clig,+kern",size="18pt"] ` I get this error: `Using code at: /usr/local/share/lua/5.2/sile/classes/fontproof/init.lua:127: attempt to concatenate field 'family' (a nil value)`
> 
> Other test files give me errors like:` Failed to load any working font manager`  or `Using code at: /usr/share/sile/outputters/libtexpdf.lua:30: attempt to index field 'paperSize' (a nil value)`
> 
> What  am I missing? What am I doing wrong? I'm just trying `fontproof tests/document.sil -f "./results/font-file.ttf -o results/example-result.pdf`
> 
> It would be ideal to be able to reuse existing .sil documents which have `\setTestFont[params]` and not to have to change them all. 
> 
> How do I set the family field or the font manager? Isn't the papersize field already defined in the package? 
> 
> One simple example is https://github.com/silnrsi/font-andika-mtihani/blob/master/tests/Latin.sil 
> 
> Thank you for any insights and tips. 
> 
> Also I'm quite happy if fontproof just becomes an in-tree package/class and is bundled inside SILE itself. IMHO there is no big need for it to be a standalone package. 
> 
> Çok teşekkür ederim!

**Comment by alerque** [comment]
This is about to get marked as closed by PR #40 which I think covers most of this by fixing the bug you hit and adding a feature besides. Uncovered are...

* Whatever your deal was with "font manager". That sounds like SILE itself isn't installed/configured correctly on the system. I'm happy to look into that too but I'll need more information about the installation. Also lets check that `sile` itself works for normal SILE-ish things and report that on the SILE issue tracker if there is a problem. If `sile` works by itself and `fontproof` invocations are fouling it up do open a new issue here with more info. The font manager is something that should be discovered by `./configure` time by SILE when it is built or packaged.

* Your question about font family: there is an `-F`/`--family` flag for that if you need it, but you only want to specify *one* of either *filename* or *family*, not both. The crash when it was empty was a bug and just about outputting debug information.

* Papersize settings should be inherited from the regular class. I don't see *anything* at all in FontProof so I can't track down that error. Perhaps the specific project you were testing there needs an update to SILE v0.14.x usage. Can you point me to the template or other files that threw that error? The Andika-Mithani Latin template you linked works fine for me. Open a new issue if you have details.

**Comment by n7s** [comment]
Thanks for the fixes, it works now (having also adjusted some parameters in our integration code).

**Comment by alerque** [comment]
@n7s The UFO test repository you linked me too early is full of broken stuff so I'm not 100% what your current integration code looks like, but here is one way to do it in GitLab CI: https://github.com/silnrsi/font-andika-mtihani/pull/2. Of course installing the LuaRock in the Ubuntu container would work too instead of using a separate job, but I find modular jobs that stick to a specific task easier to manage in the long run.

**Comment by n7s** [comment]
The integration changes are not pushed yet (probably next week) but I'm referring to changes needed in the smith repository. I'm going the luarocks installation route. (We are not using GitHub action or Gitlab pipelines at this stage but an existing CI setup already used for a bunch of other SIL software).
