### ISSUE TITLE
\setFontOptions class option issue

### ISSUE THREAD

**Issue by n7s** [sile-typesetter/fontproof#42]
looks like \setFontOptions also needs to accept the class option language:

See this [Padauk test document](https://github.com/silnrsi/font-padauk/blob/master/tests/issues.sil) for example: 

```
! Attempted to set an undeclared class option 'language' at /smith/font-padauk/tests/issues.sil:23:1: in \setTestFont[features="+clig,+kern",language="dflt",papersize="a4"]

error summary:
	Processing at: /smith/font-padauk/tests/issues.sil:23:1: in \setTestFont[features="+clig,+kern",language="dflt",papersize="a4"]
	Using code at: /usr/share/sile/classes/base.lua:22: Attempted to set an undeclared class option 'language'
```

on SILE v0.14.9 (Lua 5.2) FontProof installed from rockspec 2.0.4-1

Thanks!

**Comment by n7s** [comment]
yes please, could you go through the release steps? Thanks!

**Comment by alerque** [comment]
@n7s I just cut a release and made notes while I was doing it. I enabled the wiki feature and dropped my notes at [Release Checklist](https://github.com/sile-typesetter/fontproof/wiki/Release-Checklist). Feel free to adapt of course, and edit the page with however you'd like the release cycle to work. Most of the commands should be copy-pasteable and they worked for me to ship v2.0.5.

**Comment by alerque** [comment]
Bravo. At least as an observer it looks like you were able to cut v2.0.6 without a hitch. Did anything go wrong with those instructions behind the scene?

**Comment by alerque** [comment]
Glad it helped. My one request would be if you tweak anything that changes that workflow update the Wiki! I may need to do periodic releases to track SILE changes or whatever and with more than one dev cutting releases I'll be checking the docs myself when the need comes up instead of just hacking my way through.
