### ISSUE TITLE
Enable control of page orientation

### ISSUE THREAD

**Issue by devosb** [sile-typesetter/fontproof#47]
I would like to have some of the FontProof documents be in landscape mode. Using [design_horiz.sil](https://github.com/silnrsi/font-nokyung/blob/master/tests/design_horiz.sil) I changed the first line of the file to
```
\begin[class=fontproof,landscape=true]{document}
```
but that did not work so I tried re-ordering the classes
```
\begin[landscape=true,class=fontproof]{document}
```
but still did not work. Is landscape expected to work with FontProof? I see some landscape issues with SILE, and I was not sure what the status was. I am using SILE v0.14.16 (Lua 5.2) on Ubuntu 22.04 from the Launchpad PPA.

**Comment by alerque** [comment]
Option order doesn't matter, Lua doesn't report them to us in any particular order no matter what you put anyway.

I would have expected what you did to work.

**Comment by alerque** [comment]
Confirmed. The expected syntax works from plain SILE but not from the *fontproof* document class for some reason. I'll look into it.

**Comment by alerque** [comment]
Found it.
