### ISSUE TITLE
\gutenberg[] results in confusing warning messages

### ISSUE THREAD

**Issue by jvgaultney** [sile-typesetter/fontproof#9]
Since the SILE 0.10.1 update \gutenberg is producing warnings, even though the PDF seems fine.

```
sile fpGutenberg.sil
This is SILE v0.10.1
<fpGutenberg.sil>
Downloading Declaration of Faith, in Latin and the Original Greek... Done

?…" near fpGutenberg.sil:4:1: in \gutenbergtable: 0x7fb9df0d59b0 after in \paravailable at in "␤

?…" near fpGutenberg.sil:4:1: in \gutenbergtable: 0x7fb9df0d59b0 after in \par
[1] 
?…" near fpGutenberg.sil:4:1: in \gutenbergtable: 0x7fb9df0d59b0 after in \paravailable at in "␤

?…" near fpGutenberg.sil:4:1: in \gutenbergtable: 0x7fb9df0d59b0 after in \par
[2] 
! Underfull frame: 11.8329126455pt stretchiness required to fill but only 0pt available at fpGutenberg.sil: in <file> (\) after in \par

! Overfull content for frame runningHead at fpGutenberg.sil: in <file> (\) after in \par
[3] 
```

**Comment by alerque** [comment]
The overfull warning is likely something that should be fixed here in fontproof. I can't look into it right now but feel free to assign me to this issue so I don't forget. The underfull warning _might_ be a SILE issue. I opened a bug there to track it because it seems like the warning is a bit more aggressive than is useful. I would expect all warnings to be something the user should look into, and this seems like expected and desired output as-is.

**Comment by jvgaultney** [comment]
Thanks - I'll go ahead and do a release now. Thanks for your help!

**Comment by alerque** [comment]
At this point I don't think there is a bug left here. There are still underfull warnings not only in gutenberg but sometimes with the full template too, but there are also large blocks of stuff with aggressive penalties for splitting it across pages. This results in SILE preferring to leave some unfilled stuff on a page and start on a new one. This is a less-than-ideal typesetting maneuver in general but called for in this case. SILE is right to warn about it but this project has specific reasons for doing this. Also the error messaging has improved a bit, hopefully it is a little more clear. Maybe still room for improvement, but that's a SILE issue, not a FontProof one.
